[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-s"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-s"]

[target.i686-linux-android]
rustflags = ["-C", "link-arg=-s"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-s"]